// main-ui/src/app/layout/footer/footer.component.ts
import {Component, OnInit} from "@angular/core";

@Component({
  selector: 'app-footer',
  styleUrls: ['footer.css'],
  templateUrl: './footer.component.html',
})
export class FooterComponent implements OnInit {

  private year: number;

  constructor() {
    this.year = new Date().getFullYear();
  }

  ngOnInit(): void {
  }
}

<footer class="footer mt-auto py-3">
  <div class="container">
    <div class="row">
      <span class="text-muted">Copyright &#169; 2018-{{year}} Sergei Visotsky</span>
    </div>
  </div>
</footer>

// new-ui/src/Footer.tsx
import React, {Component} from "react";

export class Footer extends Component {

    render(): React.ReactElement<any, string | React.JSXElementConstructor<any>> | string | number | {} | React.ReactNodeArray | React.ReactPortal | boolean | null | undefined {
        return (
            <footer className="footer mt-auto py-3">
                <div className="container">
                    <span className="text-muted">Copyright &#169; 2018-2019 Sergei Visotsky</span>
                </div>
            </footer>
        );
    }
}
